### PR TITLE
V1 Update

### PR DESCRIPTION
**Pull request by 0xc0de4c0ffee**
Still WIP,
removing all CCIP2 like feature to make simple web3 IPFS gateway.

- [x] new format `<bytesX>.<bytes16>.<bytes16>.ipfs2.eth.limo`
- [x] base32 decoder
- [x] base36 decoder (needs optimization @ ~450k view gas)
- [x] add off-chain records for "ipfs2.eth"
- [x] Full Tests
- [ ] Helper function & final clean up

### CODE REVIEW

**Comment by sshmatrix** [comment]
Which helper function is missing?

**Comment by 0xc0de4c0ffee** [comment]
> Which helper function is missing?

our list of default contract management functions 
and also possible utils function to redirect all non-contenthash requests to ccip2.eth.

**Comment by 0xc0de4c0ffee** [comment]
@sshmatrix give it a try, & merge for testnet if you're satisfied, ..then we can do final checks before mainnet.

I'm bit-cheating with redirect to ccip2.eth for all ens records except contenthash 😆 
ccip2.eth is using ipfs2.eth.limo as primary gateway for *.eth, 
& ipfs2.eth is using ccip2.eth as records manager for *.ipfs2.eth.

**Comment by sshmatrix** [comment]
Awesome! I am on it 🚀

**Pull request merged**
